[package]
name = "signextend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
revm = { git = "https://github.com/flyq/revm-debug", rev = "b8e712f", default-features = false }
