[package]
name = "signextend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
revm = { path = "/Users/flyq/workspace/github/flyq/revm/crates/revm", default-features = false }
